name: responsive_magic_ui
description: Fully automatic responsive layout engine.
version: 0.1.0

topics:
  - dart
  - flutter
  - layout
  - mobile
  - pub
  - responsive
  - responsive-magic-ui
  - ui
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/NPM-Packages-Modules/responsive_magic_ui
