name: app_flow_orchestrator
description: Visual screen flow/state orchestration engine.
version: 0.1.0

topics:
  - app-flow-orchestrator
  - dart
  - flutter
  - mobile
  - navigation
  - pub
  - routing
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/NPM-Packages-Modules/app_flow_orchestrator
